export const actionTypes = {
  DISCOVER_EDUCATION_INIT: 'EDUCATION_PAGE/DISCOVER_EDUCATION_INIT',
  DISCOVER_EDUCATION_CERTIFICATES: 'EDUCATION_PAGE/DISCOVER_EDUCATION_CERTIFICATES',
  DISCOVER_EDUCATION_INFO: 'EDUCATION_PAGE/DISCOVER_EDUCATION_INFO',
};
