export const actionTypes = {
  DISCOVER_HOME_PAGE: 'HOME_PAGE/DISCOVER_HOME_PAGE',
  DISCOVER_NAME: 'HOME_PAGE/DISCOVER_NAME',
  DISCOVER_POSITION: 'HOME_PAGE/DISCOVER_POSITION',
  DISCOVER_LOCATION: 'HOME_PAGE/DISCOVER_LOCATION',
  DISCOVER_CONTACT_INFO: 'HOME_PAGE/DISCOVER_CONTACT_INFO',
  DISCOVER_AGE: 'HOME_PAGE/DISCOVER_AGE',
  DISCOVER_NATIONALITY: 'HOME_PAGE/DISCOVER_NATIONALITY',
  DISCOVER_ABOUT_ME: 'HOME_PAGE/DISCOVER_ABOUT_ME',
  DISCOVER_LANGUAGES: 'HOME_PAGE/DISCOVER_LANGUAGES',
  DISCOVER_HOBBIES: 'HOME_PAGE/DISCOVER_HOBBIES',
};
