import {
  educationKNU,
  UC_R7UXWZ3C,
  UC_LAVISYK1,
  UC_DNGQKOB0,
  UC_B6BARC8V,
  UC_BQ81OBOU,
  C_11467555,
  UC_H1HUC3GV,
  UC_AVLNUEII,
  UC_0FOZNHTE,
  UC_OH7XPMOP,
  GH93LKLL72BR,
  QYHRQW9NWKE9,
  AFGWZT2CB22S,
  Z4Q9VTM8AZ8P,
  US429DPCXALK,
  MQ6U87EN8FJU,
  RTSCG3HHW68L,
  GRYLEUQ5XCE4,
  S9BBM5RGGSQF,
  TPGE89S44JYY,
  Z7RJCJRBY8TP,
  NGVHAJRPTPN6,
  Z59CZM88MUWA,
  AUK4VB65JL,
  P4BDJZHA6B,
  HKX3G4FFBV,
  C_25YXEW6ZTG,
  TDX8U42RFD,
  C_4GLJ6PWR3PPL,
  C_36Y7SM5XLJ,
  D79YE6ATRBAK,
  FGPJG6A7U4,
  C_7M84NLE5D5TW,
  ZJ27G8KF97HT,
} from '../../../images';

export const educations = [
  {
    id: 2,
    image: educationKNU,
    schoolName: 'Kyiv National Taras Shevchenko University',
    schoolLink: 'http://www.univ.kiev.ua/en/',
    degree: 'Mathematics, Master\'s degree',
    description: `
      I actively took part in a science and a sport life of the university.
      I was the captain of the main volleyball team of the university,
      played in basketball competitions, took part in powerlifting,
      arm-wrestling, triathlon competitions and others.
      Also I was on different science conferences: in Ukraine, Brazil,
      Austria, Slovakia, etc. I have two publications in the
      international science magazine.
    `,
    start: new Date('2013-09'),
    finish: new Date('2015-05'),
    location: 'Kyiv, Ukraine',
  },
  {
    id: 1,
    image: educationKNU,
    schoolName: 'Kyiv National Taras Shevchenko University',
    schoolLink: 'http://www.univ.kiev.ua/en/',
    degree: 'Mathematics, Bachelor\'s degree',
    description: `
      I actively took part in a science and a sport life of the university.
      I was the captain of the main volleyball team of the university,
      played in basketball competitions, took part in powerlifting,
      arm-wrestling, triathlon competitions and others.
      Also I was on different science conferences: in Ukraine, Brazil,
      Austria, Slovakia, etc. I have two publications in the
      international science magazine.
    `,
    start: new Date('2009-09'),
    finish: new Date('2013-05'),
    location: 'Kyiv, Ukraine',
  },
];

export const certificates = [
  {
    title: 'The Complete Developers Guide to MongoDB',
    school: 'Udemy',
    date: '2018-10-14',
    license: 'UC-R7UXWZ3C',
    image: UC_R7UXWZ3C,
    url: 'https://www.udemy.com/certificate/UC-R7UXWZ3C/',
  },
  {
    title: 'Master Jenkins CI For DevOps and Developers',
    school: 'Udemy',
    date: '2018-09-30',
    license: 'UC-LAVISYK1',
    image: UC_LAVISYK1,
    url: 'https://udemy-certificate.s3.amazonaws.com/image/UC-LAVISYK1/',
  },
  {
    title: 'React vs Angular vs Vue.js by Example',
    school: 'Udemy',
    date: '2018-08-23',
    license: 'UC-DNGQKOB0',
    image: UC_DNGQKOB0,
    url: 'https://www.udemy.com/certificate/UC-DNGQKOB0/',
  },
  {
    title: 'Advanced React and Redux: 2018 Edition',
    school: 'Udemy',
    date: '2018-07-29',
    license: 'UC-B6BARC8V',
    image: UC_B6BARC8V,
    url: 'https://www.udemy.com/certificate/UC-B6BARC8V/',
  },
  {
    title: 'Modern React with Redux',
    school: 'Udemy',
    date: '2018-05-07',
    license: 'UC-BQ81OBOU',
    image: UC_BQ81OBOU,
    url: 'https://www.udemy.com/certificate/UC-BQ81OBOU/',
  },
  {
    title: 'Test-Driven Development',
    school: 'Codecademy',
    date: '2018-04-16',
    license: '11467555',
    image: C_11467555,
    url: 'https://www.credential.net/e524eujo',
  },
  {
    title: 'The Complete Node.js Developer Course',
    school: 'Udemy',
    date: '2018-03-24',
    license: 'UC-H1HUC3GV',
    image: UC_H1HUC3GV,
    url: 'https://www.udemy.com/certificate/UC-H1HUC3GV/',
  },
  {
    title: 'AWS Essentials',
    school: 'Udemy',
    date: '2018-02-11',
    license: 'UC-AVLNUEII',
    image: UC_AVLNUEII,
    url: 'https://www.udemy.com/certificate/UC-AVLNUEII/',
  },
  {
    title: 'Automation Testing using Selenium & Katalon Studio',
    school: 'Udemy',
    date: '2018-01-18',
    license: 'UC-0FOZNHTE',
    image: UC_0FOZNHTE,
    url: 'https://www.udemy.com/certificate/UC-0FOZNHTE/',
  },
  {
    title: 'Test Automation with Katalon Studio',
    school: 'Udemy',
    date: '2018-01-12',
    license: 'UC-OH7XPMOP',
    image: UC_OH7XPMOP,
    url: 'https://www.udemy.com/certificate/UC-OH7XPMOP/',
  },
  {
    title: 'Graph Search, Shortest Paths, and Data Structures',
    school: 'Stanford University',
    date: '2017-06-18',
    license: 'GH93LKLL72BR',
    image: GH93LKLL72BR,
    url: 'https://www.coursera.org/account/accomplishments/certificate/GH93LKLL72BR',
  },
  {
    title: 'Divide and Conquer, Sorting and Searching, and Randomized Algorithms',
    school: 'Stanford University',
    date: '2017-05-05',
    license: 'QYHRQW9NWKE9',
    image: QYHRQW9NWKE9,
    url: 'https://www.coursera.org/account/accomplishments/certificate/QYHRQW9NWKE9',
  },
  {
    title: 'Game Development for Modern Platforms',
    school: 'Michigan University',
    date: '2016-07-12',
    license: 'AFGWZT2CB22S',
    image: AFGWZT2CB22S,
    url: 'https://www.coursera.org/account/accomplishments/certificate/AFGWZT2CB22S',
  },
  {
    title: 'World Design for Video Games',
    school: 'California Institute of the Arts',
    date: '2016-11-29',
    license: 'Z4Q9VTM8AZ8P',
    image: Z4Q9VTM8AZ8P,
    url: 'https://www.coursera.org/account/accomplishments/certificate/Z4Q9VTM8AZ8P',
  },
  {
    title: 'Gamification',
    school: 'Wharton Online | The Wharton School',
    date: '2016-10-20',
    license: 'US429DPCXALK',
    image: US429DPCXALK,
    url: 'https://www.coursera.org/account/accomplishments/certificate/US429DPCXALK',
  },
  {
    title: 'Serious Gaming',
    school: 'Erasmus University Rotterdam',
    date: '2016-08-06',
    license: 'MQ6U87EN8FJU',
    image: MQ6U87EN8FJU,
    url: 'https://www.coursera.org/account/accomplishments/certificate/MQ6U87EN8FJU',
  },
  {
    title: 'Introduction to Marketing',
    school: 'Wharton Online | The Wharton School',
    date: '2016-07-27',
    license: 'RTSCG3HHW68L',
    image: RTSCG3HHW68L,
    url: 'https://www.coursera.org/account/accomplishments/certificate/RTSCG3HHW68L',
  },
  {
    title: 'Story and Narrative Development for Video Games',
    school: 'California Institute of the Arts',
    date: '2016-06-19',
    license: 'GRYLEUQ5XCE4',
    image: GRYLEUQ5XCE4,
    url: 'https://www.coursera.org/account/accomplishments/certificate/GRYLEUQ5XCE4',
  },
  {
    title: 'Business of Games and Entrepreneurship',
    school: 'Michigan State University',
    date: '2016-02-15',
    license: 'S9BBM5RGGSQF',
    image: S9BBM5RGGSQF,
    url: 'https://www.coursera.org/account/accomplishments/certificate/S9BBM5RGGSQF',
  },
  {
    title: 'Principles of Game Design',
    school: 'Michigan State University',
    date: '2015-11-18',
    license: 'TPGE89S44JYY',
    image: TPGE89S44JYY,
    url: 'https://www.coursera.org/account/accomplishments/certificate/TPGE89S44JYY',
  },
  {
    title: 'Programming and the Web for Beginners',
    school: 'Duke University',
    date: '2015-11-18',
    license: 'Z7RJCJRBY8TP',
    image: Z7RJCJRBY8TP,
    url: 'https://www.coursera.org/account/accomplishments/certificate/Z7RJCJRBY8TP',
  },
  {
    title: 'Introduction to Game Design',
    school: 'California Institute of the Arts',
    date: '2015-10-21',
    license: 'NGVHAJRPTPN6',
    image: NGVHAJRPTPN6,
    url: 'https://www.coursera.org/account/accomplishments/certificate/NGVHAJRPTPN6',
  },
  {
    title: 'Introduction to Game Design',
    school: 'Michigan State University',
    date: '2015-10-23',
    license: 'Z59CZM88MUWA',
    image: Z59CZM88MUWA,
    url: 'https://www.coursera.org/account/accomplishments/certificate/Z59CZM88MUWA',
  },
  {
    title: 'Introduction to Finance',
    school: 'University of Michigan',
    date: '2015-09-22',
    license: 'AUK4VB65JL',
    image: AUK4VB65JL,
    url: 'https://www.coursera.org/account/accomplishments/certificate/AUK4VB65JL',
  },
  {
    title: 'Algorithmic Thinking I',
    school: 'Rice University',
    date: '2015-10-07',
    license: 'P4BDJZHA6B',
    image: P4BDJZHA6B,
    url: 'https://www.coursera.org/account/accomplishments/certificate/P4BDJZHA6B',
  },
  {
    title: 'Principles of Computing I',
    school: 'Rice University',
    date: '2015-07-17',
    license: 'HKX3G4FFBV',
    image: HKX3G4FFBV,
    url: 'https://www.coursera.org/account/accomplishments/certificate/HKX3G4FFBV',
  },
  {
    title: 'An Introduction to Interactive Programming in Python II',
    school: 'Rice University',
    date: '2015-05-12',
    license: '25YXEW6ZTG',
    image: C_25YXEW6ZTG,
    url: 'https://www.coursera.org/account/accomplishments/certificate/25YXEW6ZTG',
  },
  {
    title: 'Beginning Game Programming with C#',
    school: 'University of Colorado',
    date: '2015-05-25',
    license: 'TDX8U42RFD',
    image: TDX8U42RFD,
    url: 'https://www.coursera.org/account/accomplishments/certificate/TDX8U42RFD',
  },
  {
    title: 'Effective Problem-Solving and Decision-Making',
    school: 'University of California, Irvine Extension',
    date: '2015-05-03',
    license: '4GLJ6PWR3PPL',
    image: C_4GLJ6PWR3PPL,
    url: 'https://www.coursera.org/account/accomplishments/certificate/4GLJ6PWR3PPL',
  },
  {
    title: 'Probability',
    school: 'University of Pennsylvania',
    date: '2015-05-02',
    license: '36Y7SM5XLJ',
    image: C_36Y7SM5XLJ,
    url: 'https://www.coursera.org/account/accomplishments/certificate/36Y7SM5XLJ',
  },
  {
    title: 'Successful Negotiation: Essential Strategies and Skills',
    school: 'University of Michigan',
    date: '2015-05-08',
    license: 'D79YE6ATRBAK',
    image: D79YE6ATRBAK,
    url: 'https://www.coursera.org/account/accomplishments/certificate/D79YE6ATRBAK',
  },
  {
    title: 'An Introduction to Interactive Programming in Python I',
    school: 'Rice University',
    date: '2015-04-03',
    license: 'FGPJG6A7U4',
    image: FGPJG6A7U4,
    url: 'https://www.coursera.org/account/accomplishments/certificate/FGPJG6A7U4',
  },
  {
    title: 'Project Management: The Basics for Success',
    school: 'University of California, Irvine Extension',
    date: '2015-04-22',
    license: '7M84NLE5D5TW',
    image: C_7M84NLE5D5TW,
    url: 'https://www.coursera.org/account/accomplishments/certificate/7M84NLE5D5TW',
  },
  {
    title: 'Work Smarter, Not Harder: Time Management for Personal & Professional Productivity',
    school: 'University of California, Irvine Extension',
    date: '2015-04-09',
    license: 'ZJ27G8KF97HT',
    image: ZJ27G8KF97HT,
    url: 'https://www.coursera.org/account/accomplishments/certificate/ZJ27G8KF97HT',
  },
];
